### ISSUE TITLE
Visual Studio project generation broken after Dep removal

### ISSUE THREAD

**Issue by peace-maker** [alliedmodders/ambuild#130]
Trying to generate project files for SourceMod fails due to a missing import which was removed in #119

``´
python ..\configure.py --no-mysql --enable-debug -s css,csgo -g vs
Traceback (most recent call last):
  File "C:\Users\Jannik\AppData\Local\Programs\Python\Python38\lib\site-packages\ambuild2\frontend\v2_2\prep.py", line 132, in Configure
    if not cm.generate(options.generator):
  File "C:\Users\Jannik\AppData\Local\Programs\Python\Python38\lib\site-packages\ambuild2\frontend\context_manager.py", line 91, in generate
    self.createGenerator(name)
  File "C:\Userspython ..\configure.py --no-mysql --enable-debug -s css,csgo -g vs
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\prep.py", line 132, in Configure
    if not cm.generate(options.generator):
  File "C:\Python38\lib\site-packages\ambuild2\frontend\context_manager.py", line 91, in generate
    self.createGenerator(name)
  File "C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\context_manager.py", line 177, in createGenerator
    from ambuild2.frontend.v2_2.vs.gen import Generator
  File "C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\vs\gen.py", line 18, in <module>
    from ambuild2.frontend.v2_2.vs import cxx
  File "C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\vs\cxx.py", line 24, in <module>
    from ambuild2.frontend.v2_2.vs import export_vcxproj
  File "C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\vs\export_vcxproj.py", line 21, in <module>
    from ambuild2.frontend.v2_2.cpp.builders import Dep
ImportError: cannot import name 'Dep' from 'ambuild2.frontend.v2_2.cpp.builders' (C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\cpp\builders.py)
Configure failed: cannot import name 'Dep' from 'ambuild2.frontend.v2_2.cpp.builders' (C:\Python38\lib\site-packages\ambuild2\frontend\v2_2\cpp\builders.py)
```

**Comment by dvander** [comment]
This should now be fixed.
