### ISSUE TITLE
TypeError while configuring sourcemod with python 3

### ISSUE THREAD

**Issue by Impact123** [alliedmodders/ambuild#16]
I tried to use python 3 for ambuild, but i've run into an error which, i think, is a bug.
I used a fresh virtual environment for ambuild and the latest sources from github.
The following is the output, which hopefully contains all information you need.

``` bash
python3 ../sourcemod/configure.py
Checking CC compiler (vendor test gcc)... ['cc', 'test.c', '-o', 'test']
found gcc version 4.7
Checking CXX compiler (vendor test gcc)... ['c++', 'test.cpp', '-o', 'testp']
found gcc version 4.7
Traceback (most recent call last):
  File "../sourcemod/configure.py", line 34, in <module>
    run.Configure()
  File "/home/impact/Sourcemod/sourcemod-virtualenv/lib/python3.2/site-packages/ambuild2/frontend/prep.py", line 121, in Configure
    if not builder.generate():
  File "/home/impact/Sourcemod/sourcemod-virtualenv/lib/python3.2/site-packages/ambuild2/frontend/base_gen.py", line 235, in generate
    self.parseBuildScripts()
  File "/home/impact/Sourcemod/sourcemod-virtualenv/lib/python3.2/site-packages/ambuild2/frontend/base_gen.py", line 165, in parseBuildScripts
    self.evalScript(root)
  File "/home/impact/Sourcemod/sourcemod-virtualenv/lib/python3.2/site-packages/ambuild2/frontend/base_gen.py", line 204, in evalScript
    exec(code, new_vars)
  File "/home/impact/Sourcemod/sourcemod/AMBuildScript", line 469, in <module>
    SM.configure()
  File "/home/impact/Sourcemod/sourcemod/AMBuildScript", line 177, in configure
    if have_clang or (have_gcc and cxx.version >= '4'):
TypeError: unorderable types: Version() >= str()
```

If you need more information, just tell me and i provide them.

**Comment by peace-maker** [comment]
This was fixed in #17
