### ISSUE TITLE
Accented characters with VS2017 (French installation)

### ISSUE THREAD

**Issue by nyuufr** [alliedmodders/ambuild#62]
OS: Windows 10
Python : 2.7
IDE : Visual Studio Community 2017 (FR)

I got this issue when executing the command "ambuild" in /sourcemod/build/:

```
Traceback (most recent call last):
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\ipc\windows.py", line 405, in processMessage
    listener.receiveMessage(channel, message)
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\ipc\process.py", line 287, in receiveMessage
    self.listener.receiveMessage(self.child, message)
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\ipc\process.py", line 186, in receiveMessage
    return self.messageMap[message['id']](child, message)
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\task.py", line 436, in <lambda>
    'results': lambda child, message: self.processResults(message),
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\task.py", line 502, in processResults
    self.spewResult(message)
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\task.py", line 485, in spewResult
    util.WriteEncodedText(sys.stdout, message['stdout'])
  File "D:\Developpements\Programmation\AlliedModders\python27\lib\site-packages\ambuild2\util.py", line 452, in WriteEncodedText
    fd.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 144: ordinal not in range(128)
Received unexpected error from child process 5764: badmsg
Build failed.
```

I added "print" in util.py l.450 and I saw compiler warnings like:

```
d:\developpements\programmation\alliedmodders\sourcemod\extensions\curl\curl-src\lib\setup_once.h(373): warning C4005: 'EWOULDBLOCK' : redéfinition de macro
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\errno.h(125): note: voir la définition précédente de 'EWOULDBLOCK'
```

It looks like characters 'é', 'è'.. are not tolerated.

---
I reinstalled VS2017 in english and this issue doesn't appear anymore.

**Comment by dvander** [comment]
I've received a few other reports that AMBuild on Python 2.7 does not handle utf-8 correctly everywhere. It's difficult to fix all of these because Python 2 is so inconsistent in how it handles string encoding.

At this point, we're recommending that Python 3 be used instead, and there are no known encoding issues with AMBuild on Python 3. (We're still supporting Python 2, but the bare minimum needed to keep our legacy build machines going.)
