### ISSUE TITLE
AMBuild is currently broken

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/ambuild#91]
#89 has broke AMBuild as evident in [AppVeyor](https://ci.appveyor.com/project/psychonic/sourcemod/builds/34647735) and [Travis-CI](https://travis-ci.org/github/alliedmodders/sourcemod/jobs/717725763)

Traceback (From AppVeyor):
```
Traceback (most recent call last):
  File "../configure.py", line 42, in <module>
    parser.Configure()
  File "c:\python27\lib\site-packages\ambuild2\frontend\v2_1\prep.py", line 154, in Configure
    from ambuild2.frontend.v2_1.context_manager import ContextManager
  File "c:\python27\lib\site-packages\ambuild2\frontend\v2_1\context_manager.py", line 28, in <module>
    from ambuild2.frontend.v2_1.cpp import detect
  File "c:\python27\lib\site-packages\ambuild2\frontend\v2_1\cpp\__init__.py", line 1, in <module>
    from ambuild2.frontend.v2_1.cpp.compiler import Compiler
  File "c:\python27\lib\site-packages\ambuild2\frontend\v2_1\cpp\compiler.py", line 20, in <module>
    from ambuild2.frontend.v2_1.cpp import builders
  File "c:\python27\lib\site-packages\ambuild2\frontend\v2_1\cpp\builders.py", line 21, in <module>
    from ambuild2.frontend.v2_1 import cpp
ImportError: cannot import name cpp
Command exited with code 1
```

**Comment by ErikMinekus** [comment]
#88 seems to have also broken installation. It seems you have to run `pip install -r ./ambuild/requirements.txt` before `pip install ./ambuild` now, which is not indicated in the README, nor is it done in the SourceMod `checkout-deps` script.

```bash
$ python3 -m pip install ./ambuild
Processing ./ambuild
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-7ssc9ern/setuptools-git-versioning-1.1.7/setup.py", line 7, in <module>
        sys.path.pop(0)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 403, in _open
        return _open(path,mode,*args,**kw)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by dvander** [comment]
Sorry for the disruption. I've fixed the issue with #89 and reverted #88. 

I'll be adding more tests to the CI to catch stuff like this.

**Comment by dvander** [comment]
I'm not sure why the requirements.txt thing happens. I noticed a manual requirements thing was added to the smoke test, which I thought was odd, but didn't ask about it. AMBuild doesn't have any dependencies. If having dependencies means "you now need a multi-step installation process", then I don't think it's worth having that extra step just to have automatic versioning.

But since I don't fully understand what's going on with requirements.txt, I'll let WildCard say more.

**Comment by dvander** [comment]
New smoke test is checked in - and happily, caught an identical bug in the 2.0 API. So hopefully this stops me from landing bustage that obvious again :)

**Comment by WildCard65** [comment]
The requirements.txt was added because I ran into an odd issue with 3.4 where that error you saw appeared.

It's a plain text file that holds the same contents as ```setup_requires```

**Comment by WildCard65** [comment]
Ok, it seems setuptools-git-versioning should support Python 3.3 and 3.4 respectively... I'll try adding it back to AMBuild on my fork yet again and run the smoke test against 2.7-3.8 and report back here if it's feasible.

**Comment by WildCard65** [comment]
I have an error for you from GitHub actions, environment is: Windows x64 Python 3.6
```
2020-08-14T15:44:42.7861401Z Traceback (most recent call last):
2020-08-14T15:44:42.7861665Z Checking CC compiler (vendor test msvc)... ['cl', 'test.c', '-o', 'test.exe', '-nologo', '-showIncludes']
2020-08-14T15:44:42.7863046Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\prep.py", line 160, in Configure
2020-08-14T15:44:42.7863226Z found msvc version 1926
2020-08-14T15:44:42.7863673Z     if not cm.generate(options.generator):
2020-08-14T15:44:42.7863838Z Checking CXX compiler (vendor test msvc)... ['cl', 'test.cpp', '-o', 'testp.exe', '-nologo', '-showIncludes']
2020-08-14T15:44:42.7864386Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\context_manager.py", line 93, in generate
2020-08-14T15:44:42.7864544Z found msvc version 1926
2020-08-14T15:44:42.7864873Z     self.parseBuildScripts()
2020-08-14T15:44:42.7865212Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context_manager.py", line 57, in parseBuildScripts
2020-08-14T15:44:42.7865493Z     self.execContext(cx)
2020-08-14T15:44:42.7865914Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context_manager.py", line 137, in execContext
2020-08-14T15:44:42.7866193Z     exec(code, scriptGlobals)
2020-08-14T15:44:42.7866481Z   File "D:\a\ambuild\ambuild\tests\modules\AMBuildScript", line 2, in <module>
2020-08-14T15:44:42.7866739Z     builder.DetectCxx()
2020-08-14T15:44:42.7867047Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context.py", line 135, in DetectCxx
2020-08-14T15:44:42.7867337Z     self.cxx_ = self.generator_.detectCompilers(options).clone()
2020-08-14T15:44:42.7867661Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\amb2_gen.py", line 34, in detectCompilers
2020-08-14T15:44:42.7867943Z     self.compiler = self.base_compiler.clone()
2020-08-14T15:44:42.7868186Z AttributeError: 'tuple' object has no attribute 'clone'
2020-08-14T15:44:42.7868431Z Configure failed: 'tuple' object has no attribute 'clone'
2020-08-14T15:44:42.9490130Z Traceback (most recent call last):
2020-08-14T15:44:42.9490988Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 193, in _run_module_as_main
2020-08-14T15:44:42.9491484Z     "__main__", mod_spec)
2020-08-14T15:44:42.9491978Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 85, in _run_code
2020-08-14T15:44:42.9492507Z     exec(code, run_globals)
2020-08-14T15:44:42.9492816Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts\ambuild.exe\__main__.py", line 7, in <module>
2020-08-14T15:44:42.9493151Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\run.py", line 181, in cli_run
2020-08-14T15:44:42.9493428Z     if not Build(os.path.abspath(folder), options, argv):
2020-08-14T15:44:42.9493729Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\run.py", line 131, in Build
2020-08-14T15:44:42.9494000Z     with Context(buildPath, options, argv) as cx:
2020-08-14T15:44:42.9494471Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\context.py", line 40, in __init__
2020-08-14T15:44:42.9494755Z     with open(os.path.join(self.cacheFolder, 'vars'), 'rb') as fp:
2020-08-14T15:44:42.9495018Z FileNotFoundError: [Errno 2] No such file or directory: 'D:\\a\\ambuild\\ambuild\\objdir\\.ambuild2\\vars'
```

**Comment by WildCard65** [comment]
Ok, so I found out why #88 apparently broke AMBuild and it's an issue with 'setuptools-git-versioning' only IF the source distribution is chosen over the provided wheels.

I already posted an issue about it here: https://github.com/dolfinus/setuptools-git-versioning/issues/3

**Comment by dvander** [comment]
Thanks, I'll fix this error today.

**Comment by dvander** [comment]
A fix for the configure issue has been pushed.

**Comment by WildCard65** [comment]
@dvander I decided to work on a custom GH Action that's specific for AMBuild where it invokes the configure script and AMBuild as a single action line.

**Comment by WildCard65** [comment]
Closing this as it appears nothing else is broken (see #96's edit)
