### ISSUE TITLE
AMBuild Windows Error

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/ambuild#93]
@dvander I have an error for you from GitHub actions, environment is: Windows x64 Python 3.6
```
2020-08-14T15:44:42.7861401Z Traceback (most recent call last):
2020-08-14T15:44:42.7861665Z Checking CC compiler (vendor test msvc)... ['cl', 'test.c', '-o', 'test.exe', '-nologo', '-showIncludes']
2020-08-14T15:44:42.7863046Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\prep.py", line 160, in Configure
2020-08-14T15:44:42.7863226Z found msvc version 1926
2020-08-14T15:44:42.7863673Z     if not cm.generate(options.generator):
2020-08-14T15:44:42.7863838Z Checking CXX compiler (vendor test msvc)... ['cl', 'test.cpp', '-o', 'testp.exe', '-nologo', '-showIncludes']
2020-08-14T15:44:42.7864386Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\context_manager.py", line 93, in generate
2020-08-14T15:44:42.7864544Z found msvc version 1926
2020-08-14T15:44:42.7864873Z     self.parseBuildScripts()
2020-08-14T15:44:42.7865212Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context_manager.py", line 57, in parseBuildScripts
2020-08-14T15:44:42.7865493Z     self.execContext(cx)
2020-08-14T15:44:42.7865914Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context_manager.py", line 137, in execContext
2020-08-14T15:44:42.7866193Z     exec(code, scriptGlobals)
2020-08-14T15:44:42.7866481Z   File "D:\a\ambuild\ambuild\tests\modules\AMBuildScript", line 2, in <module>
2020-08-14T15:44:42.7866739Z     builder.DetectCxx()
2020-08-14T15:44:42.7867047Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\context.py", line 135, in DetectCxx
2020-08-14T15:44:42.7867337Z     self.cxx_ = self.generator_.detectCompilers(options).clone()
2020-08-14T15:44:42.7867661Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\ambuild2\frontend\v2_1\amb2_gen.py", line 34, in detectCompilers
2020-08-14T15:44:42.7867943Z     self.compiler = self.base_compiler.clone()
2020-08-14T15:44:42.7868186Z AttributeError: 'tuple' object has no attribute 'clone'
2020-08-14T15:44:42.7868431Z Configure failed: 'tuple' object has no attribute 'clone'
2020-08-14T15:44:42.9490130Z Traceback (most recent call last):
2020-08-14T15:44:42.9490988Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 193, in _run_module_as_main
2020-08-14T15:44:42.9491484Z     "__main__", mod_spec)
2020-08-14T15:44:42.9491978Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 85, in _run_code
2020-08-14T15:44:42.9492507Z     exec(code, run_globals)
2020-08-14T15:44:42.9492816Z   File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts\ambuild.exe\__main__.py", line 7, in <module>
2020-08-14T15:44:42.9493151Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\run.py", line 181, in cli_run
2020-08-14T15:44:42.9493428Z     if not Build(os.path.abspath(folder), options, argv):
2020-08-14T15:44:42.9493729Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\run.py", line 131, in Build
2020-08-14T15:44:42.9494000Z     with Context(buildPath, options, argv) as cx:
2020-08-14T15:44:42.9494471Z   File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\ambuild2\context.py", line 40, in __init__
2020-08-14T15:44:42.9494755Z     with open(os.path.join(self.cacheFolder, 'vars'), 'rb') as fp:
2020-08-14T15:44:42.9495018Z FileNotFoundError: [Errno 2] No such file or directory: 'D:\\a\\ambuild\\ambuild\\objdir\\.ambuild2\\vars'
```

**Comment by WildCard65** [comment]
Also, can you create a new repository whos' purpose is nothing but a YAML based GitHub action for invoking AMBuild?

**Comment by WildCard65** [comment]
Closing for #91
